# Buildpack API version
api = "0.9"

# Buildpack ID and metadata
[buildpack]
id = "samples/kotlin-gradle"
version = "0.0.1"
name = "Sample Kotlin Gradle Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/main/buildpacks/kotlin-gradle"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"
