# Buildpack API version
api = "0.9"

# Buildpack ID and metadata
[buildpack]
id = "samples/dotnet-framework"
version = "0.0.1"
name = "Sample .NET Framework Buildpack"

# Targets the buildpack will work with
[[targets]]
os = "windows"
[[targets.distros]]
version = "10.0.20348.1906"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.dotnet-framework-2022"
