api = "0.9"

[buildpack]
  id = "samples/dotnet-framework"
  version = "0.0.1"
  name = "Sample .NET Framework Buildpack"

[[stacks]]
  id = "io.buildpacks.samples.stacks.dotnet-framework-1809"

[[stacks]]
  id = "io.buildpacks.samples.stacks.dotnet-framework-2004"

[[stacks]]
  id = "io.buildpacks.samples.stacks.dotnet-framework-2022"
