# Buildpack API version
api = "0.9"

# Buildpack ID and metadata
[buildpack]
id = "samples/ruby-bundler"
version = "0.0.1"
name = "Sample Ruby Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/main/buildpacks/ruby-bundler"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.jammy"

[[stacks]]
id = "*"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
mixins = ["build:set=shell-utils"]
