# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "samples/hello-moon"
version = "0.0.1"
name = "Hello Moon Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/main/buildpacks/hello-moon"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.jammy"

[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"

[[stacks]]
id = "io.buildpacks.stacks.jammy"

[[stacks]]
id = "*"