# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "samples/hello-processes"
version = "0.0.1"
name = "Hello Processes Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/main/buildpacks/hello-process"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.jammy"

[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"

[[stacks]]
id = "io.buildpacks.stacks.jammy"

[[stacks]]
id = "*"